In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
rating_db = pd.read_csv("MoviesOnStreamingPlatforms_updated.csv")

In [17]:
rating_db.head()

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

In [18]:
rating_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16744 entries, 0 to 16743
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       16744 non-null  int64
 1   ID               16744 non-null  int64
 2   Title            16744 non-null  object
 3   Year             16744 non-null  int64
 4   Age              7354 non-null   object
 5   IMDb             16173 non-null  float64
 6   Rotten Tomatoes  5158 non-null   object
 7   Netflix          16744 non-null  int64
 8   Hulu             16744 non-null  int64
 9   Prime Video      16744 non-null  int64
 10  Disney+          16744 non-null  int64
 11  Type             16744 non-null  int64
 12  Directors        16018 non-null  object
 13  Genres           16469 non-null  object
 14  Country          16309 non-null  object
 15  Language         16145 non-null  object
 16  Runtime          16152 non-null  float64
dtypes: float64(2), int64(8), object(7)
memory usage: 2.2+ MB